### ISSUE TITLE
No pip command and run from root directory is disabled

### ISSUE THREAD

**Issue by essence16** [tiskw/Random-Fourier-Features#10]
as described: pip installation is not enabled. Moreover, eachtime want to run this package, has to enter this folder, which is extremely annoying. Also docker is not a widely used option for many useres.

**Comment by tiskw** [comment]
Hi @essence16,

Thank you for opening the issue and your feedback.

> pip installation is not enabled

Yes, that's right. This library is not available from pip. There are several reasons, (1) simply a lack of time to do it, (2) the installation process is not complicated, just put `rfflearn` directory to your Python path, (3) a more comprehensive test probably be necessary before registering to pip.

However, this repository is provided as open-source software. Feel free to send me a PR, or fork from this repository and modify as you like!

> eachtime want to run this package, has to enter this folder

Sorry, I'm not clear what you meant (where the "this folder" refer to?), but at first, I recommend you to put the `rfflearn` directory to your Python path and import it as [the example code](https://github.com/tiskw/random-fourier-features/tree/main/examples) do. If you can provide the details of your point, please leave a comment in this thread.

> docker is not a widely used option for many users

Docker is just an option to build an environment. You can build your own environment using the [requirements.txt](https://github.com/tiskw/random-fourier-features/blob/main/requirements.txt) as you like.

Best regards,
Tetsuya

**Comment by tiskw** [comment]
Hi @essence16 

There has been no response for more than two weeks, so I will close this issue. Feel free to re-open this issue if necessary. Also, your PR is always welcome :)

Best regards,
Tetsuya
